CREATE UNIQUE INDEX credential_one_export_uq ON credential_bundles(account_id) WHERE state='EXPORT';
DROP INDEX login_active_account_uq;
CREATE UNIQUE INDEX login_active_account_uq ON login_attempts(account_id) WHERE state IN('CREATED','STARTING_RUNTIME','STARTING_LOGIN','WAITING_FOR_USER','OAUTH_COMPLETED','VERIFYING_ACCOUNT','STARTING_EXPORT_LOGIN','WAITING_FOR_EXPORT_USER','VERIFYING_EXPORT','QUIESCING_RUNTIME','CHECKPOINTING_CREDENTIAL','CANCEL_REQUESTED');
