DROP INDEX IF EXISTS login_active_account_uq;

CREATE UNIQUE INDEX login_active_account_uq
ON login_attempts(account_id)
WHERE state IN(
 'CREATED',
 'STARTING_RUNTIME',
 'STARTING_LOGIN',
 'WAITING_FOR_USER',
 'OAUTH_COMPLETED',
 'VERIFYING_ACCOUNT',
 'QUIESCING_RUNTIME',
 'CHECKPOINTING_CREDENTIAL',
 'CANCEL_REQUESTED'
);
